#!/bin/bash
#
# check if the  simple shell tracks your history

command="history"
tmp_file="checker_tmp_file_$R"

# clean up
stop_shell

# create a pseudo-random file
echo "$command" > $tmp_file

# send commands
cat $tmp_file | "$SHELL" > "$YOUR_OUTPUT" 2> "$YOUR_ERROR" &
cat $tmp_file | sh > "$EXPECTED_OUTPUT" 2> "$EXPECTED_ERROR"

# wait
"$SLEEP" "$SLEEPSECONDS"

# check result
check_output

# print error
check_error

#clean up
stop_shell
