#!/bin/bash

smiley=":)"
command="echo $smiley"

# Clean up
stop_shell

# Run command
echo "$command" | "$SHELL" > "$YOUR_OUTPUT" 2> "$YOUR_ERROR" &
echo "$command" | sh > "$EXPECTED_OUTPUT" 2> "$EXPECTED_ERROR"

# Wait for one second
"$SLEEP" "$SLEEPSECONDS"

# Check the output
check_output

# Check the errors
check_error

# Clean up
stop_shell
