#!/bin/bash

README="SHELL-README.md"
MAN_PAGE="man_1_simple_shell_copy"
AUTHORS="SHELL-AUTHORS"

echo "Presence of a README:"
if [ -s "$README" ]; then
    print_pass
else
    print_fail
fi

echo "Presence of a man page:"
if [ -s "$MAN_PAGE" ]; then
    print_pass
else
    print_fail
fi

echo "Presence of an AUTHORS page:"
if [ -s "$AUTHORS" ]; then
    print_pass
else
    print_fail
fi
